appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: XmM6dYbtP7FUqCHis/fvtlWoqKJ+HLOLoobeDKPPZWWq1qPG2jCo66kaNCOkxcWxgyJQFWj5ZtTcYAm4J0US/lNNMBIMx8ILSkf/51rvByI1lFzimT3KtAIHK+Zchxxp8SAyKIgRyQrv1zJHOOHZ0VqcaSw9NpmVNVIIfz2Dpol2gjjMhV77kEWRlwdUr3dDsyjIpFoSf/6HXQFEFqeSvJ7wIiS5jnWT8L4ZV8LAQ7Lu23qfU5BGUs8m6wleqAWGFyeiiU8dhaPEDXha9PB7TeR54Wpm31YhG7GQ/E0XJ475z6jeI8JcE+uNhPVXyl2E5xy2NsP7sG6LJUf8Pee6D9Y/tNxuhVThlbn7GfMaqw5E6A1WmAcW0YdI9QUkNMF/O5gcLh/2Tdu36oKJJgIqQTz4AV8lcqRTsNR1IZ30SVJsZknUbn4tQTnq7wEAjY+1Zc73zv3sBx6wBoGyDjE/8ajoBqHf33nvSa9jUUbi/1afqcT7cLTSIak14SE0iqv61IAxwNbtBAss7p+pInRrArKIDc202mGuij85MdU8ELKdMOaTixntPuz8VUAQQ27wEsrveJ95lxnY3o3Pn5DTKuiTj/u6EFjkHuTqdwyIX80xTWICkTT3otAs5xi4S/lmdHzToSXQNm59ef7tkx+/d9MofrU756sWBDNKyvx+MSk=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
